Tabs -> spaces to avoid problems when pasting functions into shells that have tab-completion

diff --git a/bin/lsof-del b/bin/lsof-del
--- a/bin/lsof-del
+++ b/bin/lsof-del
@@ -4,7 +4,7 @@
 set -euo pipefail
 
 if [ "$(id -u)" -ne "0" ]; then
-	echo "Warning: not running as root, some files may be missing." >&2
+    echo "Warning: not running as root, some files may be missing." >&2
 fi
 
 # list all Linux map files that have been deleted (typically shared libraries after an upgrade)
